services:

  frontend:
    build: ./frontend
    image: ghcr.io/dainst/arachne4-frontend:${ARACHNE_IMAGE_VERSION}
    volumes:
      - phpmyadmin_data:/var/www/html/:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${SERVER_ADDRESS}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=myresolver
      - traefik.port=80
      - traefik.http.middlewares.frontend-compress.compress=true
      - traefik.http.routers.frontend.middlewares=frontend-compress
      - "com.centurylinklabs.watchtower.enable=true"
  
  backend:
    build: ./backend
    image: ghcr.io/dainst/arachne4-backend:${ARACHNE_IMAGE_VERSION}
    environment:
      - "DB_SERVER=${DB_SERVER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "SERVER_ADDRESS=${SERVER_ADDRESS}"
      - "IIPIMAGE_SERVER=frontend"
      - "ELASTICSEARCH_SERVER=elasticsearch"
    volumes:
      - archaeocloud:/media/archaeocloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${SERVER_ADDRESS}`) && PathPrefix(`/data`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=myresolver
      - traefik.port=8080
      - traefik.http.middlewares.backend-compress.compress=true
      - traefik.http.routers.backend.middlewares=backend-compress
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=arachne"
      - "MYSQL_USER=arachne"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    command: --innodb-log-file-size=256M --innodb_buffer_pool_size=12G --innodb_strict_mode=off
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    profiles:
      - with-db

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    environment:
      - "PMA_HOST=${DB_SERVER}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - phpmyadmin_data:/var/www/html/

  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=arachne4
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  iipimage:
    build: ./iipimage
    volumes:
      - archaeocloud:/media/archaeocloud

  traefik:
    image: traefik:v2.5
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=dev@dainst.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    ports:
      - "80:80"
      - "443:443"

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 60

volumes:
  db_data:
  elasticsearch_data:
  phpmyadmin_data:
  archaeocloud:
    driver_opts:
      type: cifs
      o: "user=alc01,file_mode=0777,dir_mode=0777,password=${ARCHAEOCLOUD_PASSWORD}"
      device: "//172.17.113.250/archaeocloud"
