services:

  frontend:
    build: ./frontend
    ports:
      - 8080:80
  
  backend:
    build: ./backend
    ports:
      - 8081:8080

  db:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    environment:
      - "PMA_HOST=db"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"

  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=arachne4
    ports:
      - 9200:9200
      - 9300:9300
