services:

  frontend:
    build: ./frontend
    ports:
      - 8080:80

  elasticsearch:
    build:
      context: .
      dockerfile: ./Dockerfile-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=arachne4
    ports:
      - 9200:9200
      - 9300:9300
