services:

  frontend:
    build: ./frontend
    ports:
      - 80:80
      - 8888:8888
    volumes:
      - phpmyadmin_data:/var/www/html/:ro
  
  backend:
    build: ./backend
    ports:
      - 8081:8080

  db:
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=arachne"
      - "MYSQL_USER=arachne"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      db_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    environment:
      - "PMA_HOST=db"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - phpmyadmin_data:/var/www/html/

  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=arachne4
    volumes:
      elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  iipimage:
    build: ./iipimage

volumes:
  db_data:
  elasticsearch_data:
  phpmyadmin_data:
