name: frontend

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

defaults:
  run:
    working-directory: frontend

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-frontend
  TEST_SERVER: bogusman02.uni-koeln.de

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test

      - name: Set backend URI to test server
        run: sed -i 's/document.location.host/\"'"${{ env.TEST_SERVER }}"'\"/' app/app.js

      - name: Start dev server (in background)
        run: npm start &

      - name: Run e2e tests
        run: xvfb-run -n 97 npm run e2e

      - name: Reset backend URI
        run: sed -i 's/\"'"${{ env.TEST_SERVER }}"'\"/document.location.host/' app/app.js

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "frontend"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/stable' && 'stable' || 'latest' }}
          labels: ${{ steps.meta.outputs.labels }}
